# Generated by Django 3.2.5 on 2021-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('duration', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('starring', models.TextField()),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
